### ISSUE TITLE
Add Oracle compiler to dataset

### ISSUE THREAD

**Issue by wtwhite** [binaryeq/jcompile#80]
Feedback from @behnazh-w is that there may be some differences from the OpenJDK compiler.

@jensdietrich wants to include at least one version each for the LTS versions 8, 11, 17 and 21.

**Comment by behnazh-w** [comment]
Thanks @wtwhite for documenting the feedback. Another feedback was that for JDK releases that support "--release 6", the meaning of "6" is slightly different in Oracle JDK and OpenJDK.  [JEP 247](https://openjdk.org/jeps/247) explains the `--release` option.

**Comment by wtwhite** [comment]
Thanks @behnazh-w, although the wrinkle regarding JDK 6 should not affect us as the oldest JDK version we consider is 8.

OTOH, maybe this would be a good reason to consider adding JDK 6 -- WDYT @jensdietrich? Probably most projects won't build, but some might,

**Comment by jensdietrich** [comment]
I am keen not to add older versions -- the dataset is already large, and if we decide to extend this further my preference would be to add more programs (for instance, some that use gradle). From a publication point of view, the selection method for the compilers is stronger than the one used to include projects IMO.

**Comment by wtwhite** [comment]
Hi @behnazh-w,

Do you know of any official Oracle JDK Docker images? So far I can only find https://hub.docker.com/r/anapsix/alpine-java/, which is an unofficial JDK8 image.

If there are none: Is it OK to create our own Docker images from the JDK versions at https://www.oracle.com/nz/java/technologies/downloads/ and https://www.oracle.com/nz/java/technologies/downloads/archive/? Thanks!

**Comment by behnazh-w** [comment]
Oracle's official container registry for Java is [here](https://container-registry.oracle.com/ords/f?p=113:4:110413743506245:::4:P4_REPOSITORY,AI_REPOSITORY,AI_REPOSITORY_NAME,P4_REPOSITORY_NAME,P4_EULA_ID,P4_BUSINESS_AREA_ID:583,583,Oracle%20Java%20Development%20Kit%20(JDK),Oracle%20Java%20Development%20Kit%20(JDK),1,0&cs=3KrotjktTtFDDuycheJ3K6G_lZfVLnZ4lCFONhldEiUg9L3IS6HKnwbWtefw3Wj_7640MGuSRSuRRGudVCs1g6A).

You can also build images yourself using the `Dockerfile`s in [this GitHub repo](https://github.com/oracle/docker-images/tree/main/OracleJava) from Oracle.

**Comment by wtwhite** [comment]
Thanks for the quick and helpful reply @behnazh-w, but after making an Oracle account and following the instructions at the first link, I can successfully log in but then get an error when trying to pull:
```
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ docker login container-registry.oracle.com
Username: tim.white@vuw.ac.nz
Password: 
WARNING! Your password will be stored unencrypted in /home/wtwhite/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ docker pull container-registry.oracle.com/java/jdk:latest
Error response from daemon: pull access denied for container-registry.oracle.com/java/jdk, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

`docker pull` gives me a different error if I am logged out:
```
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ docker logout container-registry.oracle.com
Removing login credentials for container-registry.oracle.com
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ docker pull container-registry.oracle.com/java/jdk:latest
Error response from daemon: Head "https://container-registry.oracle.com/v2/java/jdk/manifests/latest": unauthorized: authentication required
```

Are you able to run `docker pull` successfully after logging in? (I think either the registry does not exist, or I don't have access to it despite the apparent success of running `docker login`.)

**Comment by wtwhite** [comment]
@behnazh-w please disregard the above -- I just hadn't accepted the Oracle Standard Terms on the website. `docker pull` is now working for me 😄

**Comment by wtwhite** [comment]
A first test build of `commons-io-2.7` using the official Oracle docker image for JDK 11.0.19 (`docker pull container-registry.oracle.com/java/jdk:11.0.19-ol8-amd64`, found on [this page](https://container-registry.oracle.com/ords/ocr/ba/java/jdk)) succeeds:

```
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ time make jars/openjdk-11.0.19/commons-io-2.7.jar.done
--snip--
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ time make jars/oraclejdk-11.0.19/commons-io-2.7.jar.done
--snip--
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ find jars -ls
 27808763      4 drwxrwxr-x   4 wtwhite  wtwhite      4096 Jun 13 13:57 jars
 27809120      4 drwxrwxr-x   2 wtwhite  wtwhite      4096 Jun 13 13:58 jars/oraclejdk-11.0.19
 27811473    268 -rw-rw-r--   1 wtwhite  wtwhite    274107 Jun 13 13:58 jars/oraclejdk-11.0.19/commons-io-2.7.jar
 27811475      0 -rw-rw-r--   1 wtwhite  wtwhite         0 Jun 13 13:58 jars/oraclejdk-11.0.19/commons-io-2.7.jar.generated-sources
 27811477     32 -rw-rw-r--   1 wtwhite  wtwhite     30882 Jun 13 13:58 jars/oraclejdk-11.0.19/commons-io-2.7.jar.bytecode-features
   292940    444 -rw-rw-r--   1 wtwhite  wtwhite    453139 Jun 13 13:58 jars/oraclejdk-11.0.19/commons-io-2.7-tests.jar
 27809123      0 -rw-rw-r--   1 wtwhite  wtwhite         0 Jun 13 13:58 jars/oraclejdk-11.0.19/commons-io-2.7.jar.done
 27808765      4 drwxrwxr-x   2 wtwhite  wtwhite      4096 Jun 13 13:47 jars/openjdk-11.0.19
 27811457    268 -rw-rw-r--   1 wtwhite  wtwhite    274107 Jun 13 13:47 jars/openjdk-11.0.19/commons-io-2.7.jar
 27811459      0 -rw-rw-r--   1 wtwhite  wtwhite         0 Jun 13 13:47 jars/openjdk-11.0.19/commons-io-2.7.jar.generated-sources
 27811461     32 -rw-rw-r--   1 wtwhite  wtwhite     30882 Jun 13 13:47 jars/openjdk-11.0.19/commons-io-2.7.jar.bytecode-features
   291742    444 -rw-rw-r--   1 wtwhite  wtwhite    453139 Jun 13 13:47 jars/openjdk-11.0.19/commons-io-2.7-tests.jar
 27809011      0 -rw-rw-r--   1 wtwhite  wtwhite         0 Jun 13 13:47 jars/openjdk-11.0.19/commons-io-2.7.jar.done
```

It produces a jar that is identical to what we get for our existing OpenJDK 11.0.19 build except for a timestamp in the manifest:
```
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ unzip -lv jars/openjdk-11.0.19/commons-io-2.7.jar|perl -lpe 's/ \d\d:\d\d / XX:XX /' > openjdk_jar_listing_normalised.txt
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ unzip -lv jars/oraclejdk-11.0.19/commons-io-2.7.jar|perl -lpe 's/ \d\d:\d\d / XX:XX /' > oraclejdk_jar_listing_normalised.txt
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ diff *_normalised.txt
1c1
< Archive:  jars/openjdk-11.0.19/commons-io-2.7.jar
---
> Archive:  jars/oraclejdk-11.0.19/commons-io-2.7.jar
4c4
<     1855  Defl:N      686  63% 2024-06-13 XX:XX 8c81ff5f  META-INF/MANIFEST.MF
---
>     1855  Defl:N      686  63% 2024-06-13 XX:XX 85760f8c  META-INF/MANIFEST.MF
wtwhite@wtwhite-vuw-vm:~/code/jcompile$ diff <(unzip -p jars/openjdk-11.0.19/commons-io-2.7.jar META-INF/MANIFEST.MF) <(unzip -p jars/oraclejdk-11.0.19/commons-io-2.7.jar META-INF/MANIFEST.MF)
11c11
< Bnd-LastModified: 1718243254004
---
> Bnd-LastModified: 1718243880897
```

The next step is to build all projects using several Oracle JDK versions, matched as closely as possible to existing compiler versions we use. (My gut feeling is we'll see similarly similar results.)
